# For Exploratory Data Analysis

## Pre-Requistics
### Create new conda environment
`conda create --name hdbenv python=3.11`

### Switch to new hdbenv conda environment
`conda activate hdbenv

### Install pandas

`conda install pandas`

In [17]:
import pandas as pd  
  
# Load the dataset  
# df = pd.read_csv('./data/resale_transactions.csv')
df = pd.read_csv('./data/resale_transactions.csv')

In [18]:
df

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
0,1,2018-05,5 ROOM,118,PASIR RIS ST 11,07 TO 09,123.0,1989,70 years 03 months,488000.0,17,5,PASIR RIS,Improved
1,2,2016-10,4 ROOM,101,RIVERVALE WALK,01 TO 03,100.0,1999,81,345000.0,21,8,SENGKANG,Model A
2,3,2018-10,5 ROOM,688A,CHOA CHU KANG DR,19 TO 21,110.0,2002,82 years 06 months,370000.0,9,5,CHOA CHU KANG,Improved
3,4,2015-12,4 ROOM,130,LOR AH SOO,13 TO 15,103.0,1984,67,432000.0,12,8,HOUGANG,Model A
4,5,2017-09,5 ROOM,533,SERANGOON NTH AVE 4,07 TO 09,122.0,1992,74 years 02 months,500000.0,22,5,SERANGOON,Improved
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88683,39106,2017-01,5 ROOM,238,YISHUN RING RD,01 TO 03,121.0,1985,67 years 07 months,380000.0,26,5,YISHUN,Improved
88684,13297,2016-04,4 ROOM,425,SERANGOON AVE 1,10 TO 12,113.0,1989,72,626000.0,22,8,SERANGOON,Model A
88685,8230,2016-09,4 ROOM,213B,COMPASSVALE LANE,10 TO 12,95.0,2012,95,435000.0,21,13,SENGKANG,Premium Apartment
88686,956,2016-04,3 ROOM,1,MARSILING DR,10 TO 12,65.0,-1974,57,250000.0,25,5,WOODLANDS,Improved
88687,25811,2015-07,3 ROOM,37,CHAI CHEE AVE,07 TO 09,66.0,-1983,66,310000.0,2,5,BEDOK,Improved

In [19]:
df.head()

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
0,1,2018-05,5 ROOM,118,PASIR RIS ST 11,07 TO 09,123.0,1989,70 years 03 months,488000.0,17,5,PASIR RIS,Improved
1,2,2016-10,4 ROOM,101,RIVERVALE WALK,01 TO 03,100.0,1999,81,345000.0,21,8,SENGKANG,Model A
2,3,2018-10,5 ROOM,688A,CHOA CHU KANG DR,19 TO 21,110.0,2002,82 years 06 months,370000.0,9,5,CHOA CHU KANG,Improved
3,4,2015-12,4 ROOM,130,LOR AH SOO,13 TO 15,103.0,1984,67,432000.0,12,8,HOUGANG,Model A
4,5,2017-09,5 ROOM,533,SERANGOON NTH AVE 4,07 TO 09,122.0,1992,74 years 02 months,500000.0,22,5,SERANGOON,Improved

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 88688 entries, 0 to 88687
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   88688 non-null  int64
 1   month                88688 non-null  str
 2   flat_type            88688 non-null  str
 3   block                88688 non-null  str
 4   street_name          88688 non-null  str
 5   storey_range         88688 non-null  str
 6   floor_area_sqm       88688 non-null  float64
 7   lease_commence_date  88688 non-null  int64
 8   remaining_lease      88688 non-null  str
 9   resale_price         88688 non-null  float64
 10  town_id              88688 non-null  int64
 11  flatm_id             88688 non-null  int64
 12  town_name            87905 non-null  str
 13  flatm_name           88174 non-null  str
dtypes: float64(2), int64(4), str(8)
memory usage: 9.5 MB

In [21]:
# Detecting Missing Values

df.isnull().sum()

id                       0
month                    0
flat_type                0
block                    0
street_name              0
storey_range             0
floor_area_sqm           0
lease_commence_date      0
remaining_lease          0
resale_price             0
town_id                  0
flatm_id                 0
town_name              783
flatm_name             514
dtype: int64

In [22]:
# Descriptive Statistics
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,88688.0,42233.303739,24376.312037,1.0,21136.75,42228.5,63339.25,84465.0
floor_area_sqm,88688.0,97.520444,24.197379,31.0,76.00,96.0,112.00,280.0
lease_commence_date,88688.0,1570.225352,1226.315949,-2016.0,1980.00,1988.0,2000.00,2016.0
resale_price,88688.0,438679.303299,146670.254508,160000.0,335000.00,408000.0,505000.00,1200000.0
town_id,88688.0,14.631337,8.032285,1.0,8.00,15.0,22.00,26.0
flatm_id,88688.0,8.889185,3.906898,1.0,5.00,8.0,12.00,21.0

In [23]:
df.describe()

,id,floor_area_sqm,lease_commence_date,resale_price,town_id,flatm_id
count,88688.000000,88688.000000,88688.000000,8.868800e+04,88688.000000,88688.000000
mean,42233.303739,97.520444,1570.225352,4.386793e+05,14.631337,8.889185
std,24376.312037,24.197379,1226.315949,1.466703e+05,8.032285,3.906898
min,1.000000,31.000000,-2016.000000,1.600000e+05,1.000000,1.000000
25%,21136.750000,76.000000,1980.000000,3.350000e+05,8.000000,5.000000
50%,42228.500000,96.000000,1988.000000,4.080000e+05,15.000000,8.000000
75%,63339.250000,112.000000,2000.000000,5.050000e+05,22.000000,12.000000
max,84465.000000,280.000000,2016.000000,1.200000e+06,26.000000,21.000000

In [24]:
# Identifying Duplicates 🙍🙍
df.duplicated().sum()

np.int64(4223)

In [25]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
88683     True
88684     True
88685     True
88686     True
88687     True
Length: 88688, dtype: bool

In [26]:
# Identifying and Sorting Duplicates
df[df.duplicated(keep=False)].sort_values(by=list(df.columns))

,id,month,flat_type,block,street_name,storey_range,floor_area_sqm,lease_commence_date,remaining_lease,resale_price,town_id,flatm_id,town_name,flatm_name
103,104,2016-09,3 ROOM,201E,TAMPINES ST 23,04 TO 06,68.0,-1987,70,305000.0,23,12,TAMPINES,New Generation
88570,104,2016-09,3 ROOM,201E,TAMPINES ST 23,04 TO 06,68.0,-1987,70,305000.0,23,12,TAMPINES,New Generation
106,107,2015-08,4 ROOM,146,SERANGOON NTH AVE 1,13 TO 15,83.0,-1987,70,355000.0,22,17,SERANGOON,Simplified
88156,107,2015-08,4 ROOM,146,SERANGOON NTH AVE 1,13 TO 15,83.0,-1987,70,355000.0,22,17,SERANGOON,Simplified
114,115,2017-03,4 ROOM,274D,PUNGGOL PL,16 TO 18,93.0,2013,95 years 04 months,560000.0,18,13,PUNGGOL,Premium Apartment
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87372,84427,2019-01,5 ROOM,348D,YISHUN AVE 11,13 TO 15,112.0,2013,93 years 09 months,758000.0,26,4,YISHUN,DBSS
84428,84429,2018-10,4 ROOM,838,HOUGANG CTRL,04 TO 06,100.0,-1997,77 years 05 months,530000.0,12,8,HOUGANG,Model A
85835,84429,2018-10,4 ROOM,838,HOUGANG CTRL,04 TO 06,100.0,-1997,77 years 05 months,530000.0,12,8,HOUGANG,Model A
84461,84462,2015-06,5 ROOM,596A,ANG MO KIO ST 52,07 TO 09,110.0,2002,86,760000.0,1,5,ANG MO KIO,Improved
87186,84462,2015-06,5 ROOM,596A,ANG MO KIO ST 52,07 TO 09,110.0,2002,86,760000.0,1,5,ANG MO KIO,Improved

In [27]:
# Removing Duplicates
df.drop_duplicates(inplace=True)

In [ ]:
# number of duplicates after removing duplicates
df.duplicated().sum()

np.int64(0)